#
# Theme Settings
#

theme: jekyll-theme-minimal
# theme                  : "minimal-mistakes-jekyll"

# Site settings
title: MZLabs
description: John Mount and Nina Zumel
logo: /assets/img/composite.jpg